"""empty message

Revision ID: 147acb184080
Revises: da341e57eb1d
Create Date: 2025-05-20 17:17:40.449552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147acb184080'
down_revision = 'da341e57eb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass
    # ### end Alembic commands ###
